services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-gastos-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: sistema-gastos-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
    driver: local